DROP TABLE IF EXISTS municipio;
CREATE TABLE municipio (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cd_municipio VARCHAR(3) NOT NULL,
  de_municipio VARCHAR(200) NOT NULL,
  ds_link TEXT
);
INSERT INTO "municipio" VALUES(1,'001','Água Branca','agua-branca');
INSERT INTO "municipio" VALUES(2,'002','Aguiar','aguiar');
INSERT INTO "municipio" VALUES(3,'003','Alagoa Grande','alagoa-grande');
INSERT INTO "municipio" VALUES(4,'004','Alagoa Nova','alagoa-nova');
INSERT INTO "municipio" VALUES(5,'005','Alagoinha','alagoinha');
INSERT INTO "municipio" VALUES(6,'006','Alcantil','alcantil');
INSERT INTO "municipio" VALUES(7,'007','Algodão de Jandaíra','algodao-de-jandaira');
INSERT INTO "municipio" VALUES(8,'008','Alhandra','alhandra');
INSERT INTO "municipio" VALUES(9,'009','Amparo','amparo');
INSERT INTO "municipio" VALUES(10,'010','Aparecida','aparecida');
INSERT INTO "municipio" VALUES(11,'011','Araçagi','aracagi');
INSERT INTO "municipio" VALUES(12,'012','Arara','arara');
INSERT INTO "municipio" VALUES(13,'013','Araruna','araruna');
INSERT INTO "municipio" VALUES(14,'014','Areia','areia');
INSERT INTO "municipio" VALUES(15,'015','Areia de Baraúnas','areia-de-baraunas');
INSERT INTO "municipio" VALUES(16,'016','Areial','areial');
INSERT INTO "municipio" VALUES(17,'017','Aroeiras','aroeiras');
INSERT INTO "municipio" VALUES(18,'018','Assunção','assuncao');
INSERT INTO "municipio" VALUES(19,'019','Baía da Traição','baia-da-traicao');
INSERT INTO "municipio" VALUES(20,'020','Bananeiras','bananeiras');
INSERT INTO "municipio" VALUES(21,'021','Baraúna','barauna');
INSERT INTO "municipio" VALUES(22,'022','Barra de Santa Rosa','barra-de-santa-rosa');
INSERT INTO "municipio" VALUES(23,'023','Barra de Santana','barra-de-santana');
INSERT INTO "municipio" VALUES(24,'024','Barra de São Miguel','barra-de-sao-miguel');
INSERT INTO "municipio" VALUES(25,'025','Bayeux','bayeux');
INSERT INTO "municipio" VALUES(26,'026','Belém','belem');
INSERT INTO "municipio" VALUES(27,'027','Belém do Brejo do Cruz','belem-do-brejo-do-cruz');
INSERT INTO "municipio" VALUES(28,'028','Bernardino Batista','bernardino-batista');
INSERT INTO "municipio" VALUES(29,'029','Boa Ventura','boa-ventura');
INSERT INTO "municipio" VALUES(30,'030','Boa Vista','boa-vista');
INSERT INTO "municipio" VALUES(31,'031','Bom Jesus','bom-jesus');
INSERT INTO "municipio" VALUES(32,'032','Bom Sucesso','bom-sucesso');
INSERT INTO "municipio" VALUES(33,'033','Bonito de Santa Fé','bonito-de-santa-fe');
INSERT INTO "municipio" VALUES(34,'034','Boqueirão','boqueirao');
INSERT INTO "municipio" VALUES(35,'035','Borborema','borborema');
INSERT INTO "municipio" VALUES(36,'036','Brejo do Cruz','brejo-do-cruz');
INSERT INTO "municipio" VALUES(37,'037','Brejo dos Santos','brejo-dos-santos');
INSERT INTO "municipio" VALUES(38,'038','Caaporã','caapora');
INSERT INTO "municipio" VALUES(39,'039','Cabaceiras','cabaceiras');
INSERT INTO "municipio" VALUES(40,'040','Cabedelo','cabedelo');
INSERT INTO "municipio" VALUES(41,'041','Cachoeira dos Índios','cachoeira-dos-indios');
INSERT INTO "municipio" VALUES(42,'042','Cacimba de Areia','cacimba-de-areia');
INSERT INTO "municipio" VALUES(43,'043','Cacimba de Dentro','cacimba-de-dentro');
INSERT INTO "municipio" VALUES(44,'044','Cacimbas','cacimbas');
INSERT INTO "municipio" VALUES(45,'045','Caiçara','caicara');
INSERT INTO "municipio" VALUES(46,'046','Cajazeiras','cajazeiras');
INSERT INTO "municipio" VALUES(47,'047','Cajazeirinhas','cajazeirinhas');
INSERT INTO "municipio" VALUES(48,'048','Caldas Brandão','caldas-brandao');
INSERT INTO "municipio" VALUES(49,'049','Camalaú','camalau');
INSERT INTO "municipio" VALUES(50,'050','Campina Grande','campina-grande');
INSERT INTO "municipio" VALUES(51,'051','Campo de Santana','campo-de-santana');
INSERT INTO "municipio" VALUES(52,'052','Capim','capim');
INSERT INTO "municipio" VALUES(53,'053','Caraúbas','caraubas');
INSERT INTO "municipio" VALUES(54,'054','Carrapateira','carrapateira');
INSERT INTO "municipio" VALUES(55,'055','Casserengue','casserengue');
INSERT INTO "municipio" VALUES(56,'056','Catingueira','catingueira');
INSERT INTO "municipio" VALUES(57,'057','Catolé do Rocha','catole-do-rocha');
INSERT INTO "municipio" VALUES(58,'058','Caturité','caturite');
INSERT INTO "municipio" VALUES(59,'059','Conceição','conceicao');
INSERT INTO "municipio" VALUES(60,'060','Condado','condado');
INSERT INTO "municipio" VALUES(61,'061','Conde','conde');
INSERT INTO "municipio" VALUES(62,'062','Congo','congo');
INSERT INTO "municipio" VALUES(63,'063','Coremas','coremas');
INSERT INTO "municipio" VALUES(64,'064','Coxixola','coxixola');
INSERT INTO "municipio" VALUES(65,'065','Cruz do Espírito Santo','cruz-do-espirito-santo');
INSERT INTO "municipio" VALUES(66,'066','Cubati','cubati');
INSERT INTO "municipio" VALUES(67,'067','Cuité','cuite');
INSERT INTO "municipio" VALUES(68,'068','Cuité de Mamanguape','cuite-de-mamanguape');
INSERT INTO "municipio" VALUES(69,'069','Cuitegi','cuitegi');
INSERT INTO "municipio" VALUES(70,'070','Curral de Cima','curral-de-cima');
INSERT INTO "municipio" VALUES(71,'071','Curral Velho','curral-velho');
INSERT INTO "municipio" VALUES(72,'072','Damião','damiao');
INSERT INTO "municipio" VALUES(73,'073','Desterro','desterro');
INSERT INTO "municipio" VALUES(74,'074','Diamante','diamante');
INSERT INTO "municipio" VALUES(75,'075','Dona Inês','dona-ines');
INSERT INTO "municipio" VALUES(76,'076','Duas Estradas','duas-estradas');
INSERT INTO "municipio" VALUES(77,'077','Emas','emas');
INSERT INTO "municipio" VALUES(78,'078','Esperança','esperanca');
INSERT INTO "municipio" VALUES(79,'079','Fagundes','fagundes');
INSERT INTO "municipio" VALUES(80,'080','Frei Martinho','frei-martinho');
INSERT INTO "municipio" VALUES(81,'081','Gado Bravo','gado-bravo');
INSERT INTO "municipio" VALUES(82,'082','Guarabira','guarabira');
INSERT INTO "municipio" VALUES(83,'083','Gurinhém','gurinhem');
INSERT INTO "municipio" VALUES(84,'084','Gurjão','gurjao');
INSERT INTO "municipio" VALUES(85,'085','Ibiara','ibiara');
INSERT INTO "municipio" VALUES(86,'086','Igaracy','igaracy');
INSERT INTO "municipio" VALUES(87,'087','Imaculada','imaculada');
INSERT INTO "municipio" VALUES(88,'088','Ingá','inga');
INSERT INTO "municipio" VALUES(89,'089','Itabaiana','itabaiana');
INSERT INTO "municipio" VALUES(90,'090','Itaporanga','itaporanga');
INSERT INTO "municipio" VALUES(91,'091','Itapororoca','itapororoca');
INSERT INTO "municipio" VALUES(92,'092','Itatuba','itatuba');
INSERT INTO "municipio" VALUES(93,'093','Jacaraú','jacarau');
INSERT INTO "municipio" VALUES(94,'094','Jericó','jerico');
INSERT INTO "municipio" VALUES(95,'095','João Pessoa','joao-pessoa');
INSERT INTO "municipio" VALUES(96,'096','Juarez Távora','juarez-tavora');
INSERT INTO "municipio" VALUES(97,'097','Juazeirinho','juazeirinho');
INSERT INTO "municipio" VALUES(98,'098','Junco do Seridó','junco-do-serido');
INSERT INTO "municipio" VALUES(99,'099','Juripiranga','juripiranga');
INSERT INTO "municipio" VALUES(100,'100','Juru','juru');
INSERT INTO "municipio" VALUES(101,'101','Lagoa','lagoa');
INSERT INTO "municipio" VALUES(102,'102','Lagoa de Dentro','lagoa-de-dentro');
INSERT INTO "municipio" VALUES(103,'103','Lagoa Seca','lagoa-seca');
INSERT INTO "municipio" VALUES(104,'104','Lastro','lastro');
INSERT INTO "municipio" VALUES(105,'105','Livramento','livramento');
INSERT INTO "municipio" VALUES(106,'106','Logradouro','logradouro');
INSERT INTO "municipio" VALUES(107,'107','Lucena','lucena');
INSERT INTO "municipio" VALUES(108,'108','Mãe dÁgua','mae-dagua');
INSERT INTO "municipio" VALUES(109,'109','Malta','malta');
INSERT INTO "municipio" VALUES(110,'110','Mamanguape','mamanguape');
INSERT INTO "municipio" VALUES(111,'111','Manaíra','manaira');
INSERT INTO "municipio" VALUES(112,'112','Marcação','marcacao');
INSERT INTO "municipio" VALUES(113,'113','Mari','mari');
INSERT INTO "municipio" VALUES(114,'114','Marizópolis','marizopolis');
INSERT INTO "municipio" VALUES(115,'115','Massaranduba','massaranduba');
INSERT INTO "municipio" VALUES(116,'116','Mataraca','mataraca');
INSERT INTO "municipio" VALUES(117,'117','Matinhas','matinhas');
INSERT INTO "municipio" VALUES(118,'118','Mato Grosso','mato-grosso');
INSERT INTO "municipio" VALUES(119,'119','Maturéia','matureia');
INSERT INTO "municipio" VALUES(120,'120','Mogeiro','mogeiro');
INSERT INTO "municipio" VALUES(121,'121','Montadas','montadas');
INSERT INTO "municipio" VALUES(122,'122','Monte Horebe','monte-horebe');
INSERT INTO "municipio" VALUES(123,'123','Monteiro','monteiro');
INSERT INTO "municipio" VALUES(124,'124','Mulungu','mulungu');
INSERT INTO "municipio" VALUES(125,'125','Natuba','natuba');
INSERT INTO "municipio" VALUES(126,'126','Nazarezinho','nazarezinho');
INSERT INTO "municipio" VALUES(127,'127','Nova Floresta','nova-floresta');
INSERT INTO "municipio" VALUES(128,'128','Nova Olinda','nova-olinda');
INSERT INTO "municipio" VALUES(129,'129','Nova Palmeira','nova-palmeira');
INSERT INTO "municipio" VALUES(130,'130','Olho dÁgua','olho-dagua');
INSERT INTO "municipio" VALUES(131,'131','Olivedos','olivedos');
INSERT INTO "municipio" VALUES(132,'132','Ouro Velho','ouro-velho');
INSERT INTO "municipio" VALUES(133,'133','Parari','parari');
INSERT INTO "municipio" VALUES(134,'134','Passagem','passagem');
INSERT INTO "municipio" VALUES(135,'135','Patos','patos');
INSERT INTO "municipio" VALUES(136,'136','Paulista','paulista');
INSERT INTO "municipio" VALUES(137,'137','Pedra Branca','pedra-branca');
INSERT INTO "municipio" VALUES(138,'138','Pedra Lavrada','pedra-lavrada');
INSERT INTO "municipio" VALUES(139,'139','Pedras de Fogo','pedras-de-fogo');
INSERT INTO "municipio" VALUES(140,'140','Pedro Régis','pedro-regis');
INSERT INTO "municipio" VALUES(141,'141','Piancó','pianco');
INSERT INTO "municipio" VALUES(142,'142','Picuí','picui');
INSERT INTO "municipio" VALUES(143,'143','Pilar','pilar');
INSERT INTO "municipio" VALUES(144,'144','Pilões','piloes');
INSERT INTO "municipio" VALUES(145,'145','Pilõezinhos','piloezinhos');
INSERT INTO "municipio" VALUES(146,'146','Pirpirituba','pirpirituba');
INSERT INTO "municipio" VALUES(147,'147','Pitimbu','pitimbu');
INSERT INTO "municipio" VALUES(148,'148','Pocinhos','pocinhos');
INSERT INTO "municipio" VALUES(149,'149','Poço Dantas','poco-dantas');
INSERT INTO "municipio" VALUES(150,'150','Poço de José de Moura','poco-de-jose-de-moura');
INSERT INTO "municipio" VALUES(151,'151','Pombal','pombal');
INSERT INTO "municipio" VALUES(152,'152','Prata','prata');
INSERT INTO "municipio" VALUES(153,'153','Princesa Isabel','princesa-isabel');
INSERT INTO "municipio" VALUES(154,'154','Puxinanã','puxinana');
INSERT INTO "municipio" VALUES(155,'155','Queimadas','queimadas');
INSERT INTO "municipio" VALUES(156,'156','Quixabá','quixaba');
INSERT INTO "municipio" VALUES(157,'157','Remígio','remigio');
INSERT INTO "municipio" VALUES(158,'158','Riachão','riachao');
INSERT INTO "municipio" VALUES(159,'159','Riachão do Bacamarte','riachao-do-bacamarte');
INSERT INTO "municipio" VALUES(160,'160','Riachão do Poço','riachao-do-poco');
INSERT INTO "municipio" VALUES(161,'161','Riacho de Santo Antônio','riacho-de-santo-antonio');
INSERT INTO "municipio" VALUES(162,'162','Riacho dos Cavalos','riacho-dos-cavalos');
INSERT INTO "municipio" VALUES(163,'163','Rio Tinto','rio-tinto');
INSERT INTO "municipio" VALUES(164,'164','Salgadinho','salgadinho');
INSERT INTO "municipio" VALUES(165,'165','Salgado de São Félix','salgado-de-sao-felix');
INSERT INTO "municipio" VALUES(166,'166','Santa Cecília','santa-cecilia');
INSERT INTO "municipio" VALUES(167,'167','Santa Cruz','santa-cruz');
INSERT INTO "municipio" VALUES(168,'168','Santa Helena','santa-helena');
INSERT INTO "municipio" VALUES(169,'169','Santa Inês','santa-ines');
INSERT INTO "municipio" VALUES(170,'170','Santa Luzia','santa-luzia');
INSERT INTO "municipio" VALUES(171,'171','Santa Rita','santa-rita');
INSERT INTO "municipio" VALUES(172,'172','Santa Teresinha','santa-teresinha');
INSERT INTO "municipio" VALUES(173,'173','Santana de Mangueira','santana-de-mangueira');
INSERT INTO "municipio" VALUES(174,'174','Santana dos Garrotes','santana-dos-garrotes');
INSERT INTO "municipio" VALUES(175,'175','Santarém','santarem');
INSERT INTO "municipio" VALUES(176,'176','Santo André','santo-andre');
INSERT INTO "municipio" VALUES(177,'177','São Bentinho','sao-bentinho');
INSERT INTO "municipio" VALUES(178,'178','São Bento','sao-bento');
INSERT INTO "municipio" VALUES(179,'179','São Domingos','sao-domingos');
INSERT INTO "municipio" VALUES(180,'180','São Domingos do Cariri','sao-domingos-do-cariri');
INSERT INTO "municipio" VALUES(181,'181','São Francisco','sao-francisco');
INSERT INTO "municipio" VALUES(182,'182','São João do Cariri','sao-joao-do-cariri');
INSERT INTO "municipio" VALUES(183,'183','São João do Rio do Peixe','sao-joao-do-rio-do-peixe');
INSERT INTO "municipio" VALUES(184,'184','São João do Tigre','sao-joao-do-tigre');
INSERT INTO "municipio" VALUES(185,'185','São José da Lagoa Tapada','sao-jose-da-lagoa-tapada');
INSERT INTO "municipio" VALUES(186,'186','São José de Caiana','sao-jose-de-caiana');
INSERT INTO "municipio" VALUES(187,'187','São José de Espinharas','sao-jose-de-espinharas');
INSERT INTO "municipio" VALUES(188,'188','São José de Piranhas','sao-jose-de-piranhas');
INSERT INTO "municipio" VALUES(189,'189','São José de Princesa','sao-jose-de-princesa');
INSERT INTO "municipio" VALUES(190,'190','São José do Bonfim','sao-jose-do-bonfim');
INSERT INTO "municipio" VALUES(191,'191','São José do Brejo do Cruz','sao-jose-do-brejo-do-cruz');
INSERT INTO "municipio" VALUES(192,'192','São José do Sabugi','sao-jose-do-sabugi');
INSERT INTO "municipio" VALUES(193,'193','São José dos Cordeiros','sao-jose-dos-cordeiros');
INSERT INTO "municipio" VALUES(194,'194','São José dos Ramos','sao-jose-dos-ramos');
INSERT INTO "municipio" VALUES(195,'195','São Mamede','sao-mamede');
INSERT INTO "municipio" VALUES(196,'196','São Miguel de Taipu','sao-miguel-de-taipu');
INSERT INTO "municipio" VALUES(197,'197','São Sebastião de Lagoa de Roça','sao-sebastiao-de-lagoa-de-roca');
INSERT INTO "municipio" VALUES(198,'198','São Sebastião do Umbuzeiro','sao-sebastiao-do-umbuzeiro');
INSERT INTO "municipio" VALUES(199,'199','São Vicente do Seridó','sao-vicente-do-serido');
INSERT INTO "municipio" VALUES(200,'200','Sapé','sape');
INSERT INTO "municipio" VALUES(201,'201','Serra Branca','serra-branca');
INSERT INTO "municipio" VALUES(202,'202','Serra da Raiz','serra-da-raiz');
INSERT INTO "municipio" VALUES(203,'203','Serra Grande','serra-grande');
INSERT INTO "municipio" VALUES(204,'204','Serra Redonda','serra-redonda');
INSERT INTO "municipio" VALUES(205,'205','Serraria','serraria');
INSERT INTO "municipio" VALUES(206,'206','Sertãozinho','sertaozinho');
INSERT INTO "municipio" VALUES(207,'207','Sobrado','sobrado');
INSERT INTO "municipio" VALUES(208,'208','Solânea','solanea');
INSERT INTO "municipio" VALUES(209,'209','Soledade','soledade');
INSERT INTO "municipio" VALUES(210,'210','Sossêgo','sossego');
INSERT INTO "municipio" VALUES(211,'211','Sousa','sousa');
INSERT INTO "municipio" VALUES(212,'212','Sumé','sume');
INSERT INTO "municipio" VALUES(213,'213','Taperoá','taperoa');
INSERT INTO "municipio" VALUES(214,'214','Tavares','tavares');
INSERT INTO "municipio" VALUES(215,'215','Teixeira','teixeira');
INSERT INTO "municipio" VALUES(216,'216','Tenório','tenorio');
INSERT INTO "municipio" VALUES(217,'217','Triunfo','triunfo');
INSERT INTO "municipio" VALUES(218,'218','Uiraúna','uirauna');
INSERT INTO "municipio" VALUES(219,'219','Umbuzeiro','umbuzeiro');
INSERT INTO "municipio" VALUES(220,'220','Várzea','varzea');
INSERT INTO "municipio" VALUES(221,'221','Vieirópolis','vieiropolis');
INSERT INTO "municipio" VALUES(222,'222','Vista Serrana','vista-serrana');
INSERT INTO "municipio" VALUES(223,'223','Zabelê','zabele');
