DROP TABLE IF EXISTS municipio;
CREATE TABLE municipio (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cd_municipio VARCHAR(3) NOT NULL,
  de_municipio VARCHAR(200) NOT NULL,
  ds_link TEXT
);

INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '001', 'Água Branca');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '002', 'Aguiar');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '003', 'Alagoa Grande');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '004', 'Alagoa Nova');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '005', 'Alagoinha');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '006', 'Alcantil');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '007', 'Algodão de Jandaíra');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '008', 'Alhandra');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '009', 'Amparo');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '010', 'Aparecida');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '011', 'Araçagi');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '012', 'Arara');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '013', 'Araruna');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '014', 'Areia');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '015', 'Areia de Baraúnas');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '016', 'Areial');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '017', 'Aroeiras');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '018', 'Assunção');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '019', 'Baía da Traição');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '020', 'Bananeiras');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '021', 'Baraúna');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '022', 'Barra de Santa Rosa');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '023', 'Barra de Santana');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '024', 'Barra de São Miguel');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '025', 'Bayeux');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '026', 'Belém');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '027', 'Belém do Brejo do Cruz');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '028', 'Bernardino Batista');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '029', 'Boa Ventura');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '030', 'Boa Vista');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '031', 'Bom Jesus');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '032', 'Bom Sucesso');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '033', 'Bonito de Santa Fé');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '034', 'Boqueirão');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '035', 'Borborema');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '036', 'Brejo do Cruz');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '037', 'Brejo dos Santos');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '038', 'Caaporã');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '039', 'Cabaceiras');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '040', 'Cabedelo');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '041', 'Cachoeira dos Índios');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '042', 'Cacimba de Areia');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '043', 'Cacimba de Dentro');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '044', 'Cacimbas');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '045', 'Caiçara');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '046', 'Cajazeiras');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '047', 'Cajazeirinhas');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '048', 'Caldas Brandão');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '049', 'Camalaú');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '050', 'Campina Grande');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '051', 'Campo de Santana');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '052', 'Capim');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '053', 'Caraúbas');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '054', 'Carrapateira');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '055', 'Casserengue');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '056', 'Catingueira');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '057', 'Catolé do Rocha');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '058', 'Caturité');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '059', 'Conceição');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '060', 'Condado');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '061', 'Conde');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '062', 'Congo');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '063', 'Coremas');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '064', 'Coxixola');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '065', 'Cruz do Espírito Santo');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '066', 'Cubati');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '067', 'Cuité');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '068', 'Cuité de Mamanguape');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '069', 'Cuitegi');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '070', 'Curral de Cima');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '071', 'Curral Velho');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '072', 'Damião');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '073', 'Desterro');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '074', 'Diamante');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '075', 'Dona Inês');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '076', 'Duas Estradas');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '077', 'Emas');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '078', 'Esperança');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '079', 'Fagundes');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '080', 'Frei Martinho');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '081', 'Gado Bravo');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '082', 'Guarabira');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '083', 'Gurinhém');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '084', 'Gurjão');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '085', 'Ibiara');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '086', 'Igaracy');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '087', 'Imaculada');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '088', 'Ingá');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '089', 'Itabaiana');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '090', 'Itaporanga');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '091', 'Itapororoca');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '092', 'Itatuba');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '093', 'Jacaraú');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '094', 'Jericó');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '095', 'João Pessoa');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '096', 'Juarez Távora');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '097', 'Juazeirinho');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '098', 'Junco do Seridó');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '099', 'Juripiranga');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '100', 'Juru');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '101', 'Lagoa');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '102', 'Lagoa de Dentro');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '103', 'Lagoa Seca');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '104', 'Lastro');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '105', 'Livramento');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '106', 'Logradouro');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '107', 'Lucena');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '108', 'Mãe dÁgua');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '109', 'Malta');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '110', 'Mamanguape');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '111', 'Manaíra');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '112', 'Marcação');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '113', 'Mari');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '114', 'Marizópolis');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '115', 'Massaranduba');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '116', 'Mataraca');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '117', 'Matinhas');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '118', 'Mato Grosso');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '119', 'Maturéia');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '120', 'Mogeiro');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '121', 'Montadas');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '122', 'Monte Horebe');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '123', 'Monteiro');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '124', 'Mulungu');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '125', 'Natuba');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '126', 'Nazarezinho');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '127', 'Nova Floresta');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '128', 'Nova Olinda');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '129', 'Nova Palmeira');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '130', 'Olho dÁgua');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '131', 'Olivedos');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '132', 'Ouro Velho');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '133', 'Parari');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '134', 'Passagem');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '135', 'Patos');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '136', 'Paulista');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '137', 'Pedra Branca');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '138', 'Pedra Lavrada');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '139', 'Pedras de Fogo');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '140', 'Pedro Régis');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '141', 'Piancó');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '142', 'Picuí');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '143', 'Pilar');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '144', 'Pilões');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '145', 'Pilõezinhos');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '146', 'Pirpirituba');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '147', 'Pitimbu');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '148', 'Pocinhos');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '149', 'Poço Dantas');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '150', 'Poço de José de Moura');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '151', 'Pombal');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '152', 'Prata');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '153', 'Princesa Isabel');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '154', 'Puxinanã');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '155', 'Queimadas');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '156', 'Quixabá');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '157', 'Remígio');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '158', 'Riachão');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '159', 'Riachão do Bacamarte');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '160', 'Riachão do Poço');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '161', 'Riacho de Santo Antônio');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '162', 'Riacho dos Cavalos');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '163', 'Rio Tinto');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '164', 'Salgadinho');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '165', 'Salgado de São Félix');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '166', 'Santa Cecília');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '167', 'Santa Cruz');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '168', 'Santa Helena');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '169', 'Santa Inês');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '170', 'Santa Luzia');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '171', 'Santa Rita');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '172', 'Santa Teresinha');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '173', 'Santana de Mangueira');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '174', 'Santana dos Garrotes');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '175', 'Santarém');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '176', 'Santo André');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '177', 'São Bentinho');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '178', 'São Bento');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '179', 'São Domingos');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '180', 'São Domingos do Cariri');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '181', 'São Francisco');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '182', 'São João do Cariri');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '183', 'São João do Rio do Peixe');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '184', 'São João do Tigre');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '185', 'São José da Lagoa Tapada');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '186', 'São José de Caiana');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '187', 'São José de Espinharas');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '188', 'São José de Piranhas');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '189', 'São José de Princesa');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '190', 'São José do Bonfim');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '191', 'São José do Brejo do Cruz');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '192', 'São José do Sabugi');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '193', 'São José dos Cordeiros');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '194', 'São José dos Ramos');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '195', 'São Mamede');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '196', 'São Miguel de Taipu');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '197', 'São Sebastião de Lagoa de Roça');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '198', 'São Sebastião do Umbuzeiro');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '199', 'São Vicente do Seridó');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '200', 'Sapé');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '201', 'Serra Branca');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '202', 'Serra da Raiz');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '203', 'Serra Grande');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '204', 'Serra Redonda');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '205', 'Serraria');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '206', 'Sertãozinho');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '207', 'Sobrado');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '208', 'Solânea');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '209', 'Soledade');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '210', 'Sossêgo');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '211', 'Sousa');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '212', 'Sumé');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '213', 'Taperoá');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '214', 'Tavares');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '215', 'Teixeira');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '216', 'Tenório');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '217', 'Triunfo');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '218', 'Uiraúna');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '219', 'Umbuzeiro');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '220', 'Várzea');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '221', 'Vieirópolis');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '222', 'Vista Serrana');
INSERT INTO municipio (id, cd_municipio, de_municipio) VALUES (NULL, '223', 'Zabelê');
